# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit1 = QtWidgets.QTextEdit(Dialog)
        self.textEdit1.setEnabled(True)
        self.textEdit1.setReadOnly(True)
        self.textEdit1.setObjectName("textEdit1")
        self.gridLayout.addWidget(self.textEdit1, 0, 0, 1, 2)
        self.Push_Go = QtWidgets.QPushButton(Dialog)
        self.Push_Go.setObjectName("Push_Go")
        self.gridLayout.addWidget(self.Push_Go, 1, 0, 1, 1)
        self.Push_back = QtWidgets.QPushButton(Dialog)
        self.Push_back.setObjectName("Push_back")
        self.gridLayout.addWidget(self.Push_back, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit1.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Push_Go.setText(_translate("Dialog", "继续"))
        self.Push_Go.setShortcut(_translate("Dialog", "Return"))
        self.Push_back.setText(_translate("Dialog", "导出"))
