# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(505, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.outDir = QtWidgets.QLineEdit(Dialog)
        self.outDir.setReadOnly(True)
        self.outDir.setObjectName("outDir")
        self.verticalLayout.addWidget(self.outDir)
        self.getDir = QtWidgets.QPushButton(Dialog)
        self.getDir.setObjectName("getDir")
        self.verticalLayout.addWidget(self.getDir)
        self.download = QtWidgets.QPushButton(Dialog)
        self.download.setObjectName("download")
        self.verticalLayout.addWidget(self.download)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.getDir.setText(_translate("Dialog", "选择路径"))
        self.download.setText(_translate("Dialog", "输出"))
